### ISSUE TITLE
Binaries are still linked with libomp when USE_OPENMP=OFF

### ISSUE THREAD

**Issue by yurivict** [simonpintarelli/nlcglib#13]
Version: 0.9-148-g9a1bca6
clang-14
FreeBSD 13.1

**Comment by simonpintarelli** [comment]
Thank you for the report. I've checked the cmake, nlcglib targets are not linked against openmp when `-DUSE_OPENMP=Off` is set.

I suspect nlcglib was linked against kokkos which was compiled with openmp. In this case, cmake will inherit the flags exported by kokkos. The binary will be linked against openmp, but nlcglib will not use any openmp kernels.

**Comment by yurivict** [comment]
That's a bug in kokkos then that it makes users to link to libomp.
