### ISSUE TITLE
Offline builds

### ISSUE THREAD

**Issue by matt-chan** [simonpintarelli/nlcglib#16]
Hi Simon, 

(Thank you very much for your quick replies on all the requests we've been making)

One more issue we ran into when using the offline cluster is that the CMake submodules try to fetch their git submodules at compile time. In the vanilla QE spack recipe, they build all the dependencies first so the internal builds never get turned on. 

Is there any way to do the same for q-e-sirius? The Wannier90 package is what breaks currently, but looking at `externals/`, MBD, and devxlib may also be problems.

Thank you!
Matt

**Comment by simonpintarelli** [comment]
Hi Matt,

you're welcome.

I'm not sure I understand the question correctly. As far as I can see `spack install quantum-espresso` does the same, it calls `git submodule init/update` during `cmake` stage in spack.  This is how it is done in quantum-espresso cmake and is the reason why `git` is a build dependency of `quantum-espresso` in spack.

>  In the vanilla QE spack recipe, they build all the dependencies first so the internal builds never get turned on.

I had a look at the package.py of QE, but coudn't find anything related to that. The codes in `external` (wannier90, fox, devxlib etc) don't exist as separate packages in spack. Afaik QE always wants to build them inline and cannot discover them as true external dependencies.

For building on the offline cluster,  I suspect the only workaround is to use `spack develop -p /path/to/q-e-[sirius] q-e-sirius@develop-ristretto` and previously do a `git clone --recursive` of quantum-espresso/q-e-sirius, such that the submodules in `external` are already present and checked out.

**Comment by matt-chan** [comment]
Hi Simon,

Ah yes you're right. I was mistaken that vanilla QE doesn't download any submodules. I tested on the offline cluster and it also failed. 

I ended patching out the qe submodule update cmake function. As you pointed out, a git clone recursive is enough to fetch all the dependencies. I'm going to contribute the fix back to spack mainline. Do you mind updating apply it as well if it looks good please?

Thanks!
Matt
